name: My Github Actios Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-lastets
    steps:
      - name: Hello
        run: echo "Hello, Github Actions"
      - name: Display repo name 
        run: echo "This workflow is running in ${{ github.repository}}"